# Generated by Django 6.0.3 on 2026-03-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientes_options_alter_pedidos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='estoque',
        ),
    ]
