# Generated by Django 6.0.3 on 2026-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_itempedido_delete_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descricao', models.TextField()),
                ('resumo', models.CharField(blank=True, max_length=300)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_original', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('rascunho', 'Rascunho')], default='rascunho', max_length=20)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.DeleteModel(
            name='Estoques',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
