# Generated by Django 6.0.3 on 2026-03-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone_lucide',
            field=models.CharField(blank=True, default='folder', help_text='Nome do ícone Lucide. Ex: graduation-cap, book-open, cpu', max_length=50),
        ),
    ]
