# Generated by Django 6.0.3 on 2026-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'produto')},
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', '-criado_em'], name='core_pedido_usuario_8fcef9_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status'], name='core_pedido_status_4c9167_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['status', '-criado_em'], name='core_produt_status_15c0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'status'], name='core_produt_categor_5e5bb3_idx'),
        ),
    ]
